# Generated by Django 5.2.3 on 2025-07-03 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0006_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('AULA_AO_VIVO', 'Aula ao Vivo'), ('PROVA', 'Prova'), ('ENTREGA_TRABALHO', 'Entrega de Trabalho'), ('OUTRO', 'Outro')], default='AULA_AO_VIVO', max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cursos.curso')),
            ],
            options={
                'ordering': ['data_inicio'],
            },
        ),
    ]
