### ==============================================
### TESTE DE AUTENTICAÇÃO E CURSOS
### ==============================================

###
### (1) Fazer Login e Salvar o Token de Acesso
# Esta requisição faz o login e salva o token de acesso em uma variável chamada accessToken
# @name login
POST http://127.0.0.1:8000/api/auth/token/
Content-Type: application/json

{
    //"username": "admin",
    //"password": "1234"
    //"username": "aluno_comum",
    //"password": "teste123"
    //"username": "aluno_gamer",
    //"password": "1234"
    
}

# @accessToken = {{login.response.body.access}}
###___________________________________________________
    ### 2. Inscrever aluno_gamer no Curso de ID 2
POST http://127.0.0.1:8000/api/cursos/cursos/2/inscrever/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzI1Nzg0LCJpYXQiOjE3NTEyOTY5ODQsImp0aSI6IjcxODc2OWMwNGQ0YzRiOGQ4Y2ZkYmQ0YmUyZGE2ODU4IiwidXNlcl9pZCI6NH0.iuIhljJ-jZQDAxfhP3_rFfoqP-Ez94ZDbGANylqwJaM

### Listar todas as Aulas para encontrar um ID
GET http://127.0.0.1:8000/api/cursos/aulas/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzI1Nzg0LCJpYXQiOjE3NTEyOTY5ODQsImp0aSI6IjcxODc2OWMwNGQ0YzRiOGQ4Y2ZkYmQ0YmUyZGE2ODU4IiwidXNlcl9pZCI6NH0.iuIhljJ-jZQDAxfhP3_rFfoqP-Ez94ZDbGANylqwJaM

### 3. Marcar Aula de ID 1 como concluída
POST http://127.0.0.1:8000/api/cursos/aulas/1/marcar_como_concluida/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzI1Nzg0LCJpYXQiOjE3NTEyOTY5ODQsImp0aSI6IjcxODc2OWMwNGQ0YzRiOGQ4Y2ZkYmQ0YmUyZGE2ODU4IiwidXNlcl9pZCI6NH0.iuIhljJ-jZQDAxfhP3_rFfoqP-Ez94ZDbGANylqwJaM









###
### (2) Listar Cursos (Requisição Autenticada)
# Este comando usa o token que foi salvo acima para se autenticar.

#GET http://127.0.0.1:8000/api/cursos/cursos/
#Authorization: Bearer {{accessToken}}




### (2) Listar Cursos (Com Token Manual)
GET http://127.0.0.1:8000/api/cursos/cursos/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzM3NTg1LCJpYXQiOjE3NTEzMDg3ODUsImp0aSI6IjEwZWNlNTUwYjM0MjRjNDM5Y2FlMWU1NDcyZDE0MTg3IiwidXNlcl9pZCI6NH0.PfJaya9fKXwd0QbUv2YVnDzI5iejVtLmGszHCtj5bFQ

### (2.A) Criar um Curso para o Fórum
POST http://127.0.0.1:8000/api/cursos/cursos/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMDcwNDQ2LCJpYXQiOjE3NTEwNDE2NDYsImp0aSI6IjRmM2Y1NWE4OGNlMjRlOGM4MzM5ZjA3MDhmMzRiNjg0IiwidXNlcl9pZCI6MX0.bGfJxGm7gEF-dUJS7beYmJyKPLu9fUX204G94RhbCCU

{
    "titulo": "Meu Curso para o Fórum",
    "carga_horaria": 15
}



### (3) Criar uma Nova Postagem no Fórum
POST http://127.0.0.1:8000/api/cursos/postagens/
Content-Type: application/json
Authorization: BearereyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzM2ODkyLCJpYXQiOjE3NTEzMDgwOTIsImp0aSI6IjhkMDYzY2U1OTQ3ZTRhMzU5MjI3ZTJhMjc3YWJjODEwIiwidXNlcl9pZCI6MX0.Ev4BqPSdBYnCAQqInIIFi3f6Gv-nRYUcHzpS9RKswQI


{
    "titulo": "Minha primeira postagem funcional!",
    "conteudo": "Agora sim, a API está aceitando a postagem.",
    "curso": 2
}



### Criar um Módulo para o Curso 2
POST http://127.0.0.1:8000/api/cursos/modulos/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzI1Nzg0LCJpYXQiOjE3NTEyOTY5ODQsImp0aSI6IjcxODc2OWMwNGQ0YzRiOGQ4Y2ZkYmQ0YmUyZGE2ODU4IiwidXNlcl9pZCI6NH0.iuIhljJ-jZQDAxfhP3_rFfoqP-Ez94ZDbGANylqwJaM

{
    "titulo": "Módulo de Teste para Gamificação",
    "ordem": 1,
    "curso": 2
}


### Listar Minhas Conquistas
GET http://127.0.0.1:8000/api/gamificacao/minhas-conquistas/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzI1Nzg0LCJpYXQiOjE3NTEyOTY5ODQsImp0aSI6IjcxODc2OWMwNGQ0YzRiOGQ4Y2ZkYmQ0YmUyZGE2ODU4IiwidXNlcl9pZCI6NH0.iuIhljJ-jZQDAxfhP3_rFfoqP-Ez94ZDbGANylqwJaM


### Criar a primeira Aula de Teste
POST http://127.0.0.1:8000/api/cursos/aulas/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzI1Nzg0LCJpYXQiOjE3NTEyOTY5ODQsImp0aSI6IjcxODc2OWMwNGQ0YzRiOGQ4Y2ZkYmQ0YmUyZGE2ODU4IiwidXNlcl9pZCI6NH0.iuIhljJ-jZQDAxfhP3_rFfoqP-Ez94ZDbGANylqwJaM

{
    "titulo": "Minha Primeira Aula de Teste",
    "ordem": 1,
    "modulo": 1 
}

### Marcar Aula como concluída
POST http://127.0.0.1:8000/api/cursos/aulas/1 Ryzen 7 9800X3D /marcar_como_concluida/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzI1Nzg0LCJpYXQiOjE3NTEyOTY5ODQsImp0aSI6IjcxODc2OWMwNGQ0YzRiOGQ4Y2ZkYmQ0YmUyZGE2ODU4IiwidXNlcl9pZCI6NH0.iuIhljJ-jZQDAxfhP3_rFfoqP-Ez94ZDbGANylqwJaM

### Criar a Aula de Teste dentro do Módulo de ID 2
POST http://127.0.0.1:8000/api/cursos/aulas/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzI1Nzg0LCJpYXQiOjE3NTEyOTY5ODQsImp0aSI6IjcxODc2OWMwNGQ0YzRiOGQ4Y2ZkYmQ0YmUyZGE2ODU4IiwidXNlcl9pZCI6NH0.iuIhljJ-jZQDAxfhP3_rFfoqP-Ez94ZDbGANylqwJaM

{
    "titulo": "Aula Inaugural de Teste",
    "ordem": 1,
    "modulo": 2 
}


### Listar Meu Boletim (Notas)
GET http://127.0.0.1:8000/api/avaliacoes/meu-boletim/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzM3NTg1LCJpYXQiOjE3NTEzMDg3ODUsImp0aSI6IjEwZWNlNTUwYjM0MjRjNDM5Y2FlMWU1NDcyZDE0MTg3IiwidXNlcl9pZCI6NH0.PfJaya9fKXwd0QbUv2YVnDzI5iejVtLmGszHCtj5bFQ

### Listar todas as Postagens do Fórum
GET http://127.0.0.1:8000/api/cursos/postagens/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzM3NTg1LCJpYXQiOjE3NTEzMDg3ODUsImp0aSI6IjEwZWNlNTUwYjM0MjRjNDM5Y2FlMWU1NDcyZDE0MTg3IiwidXNlcl9pZCI6NH0.PfJaya9fKXwd0QbUv2YVnDzI5iejVtLmGszHCtj5bFQ

### Criar uma Nova Postagem para Teste
POST http://127.0.0.1:8000/api/cursos/postagens/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzM3NTg1LCJpYXQiOjE3NTEzMDg3ODUsImp0aSI6IjEwZWNlNTUwYjM0MjRjNDM5Y2FlMWU1NDcyZDE0MTg3IiwidXNlcl9pZCI6NH0.PfJaya9fKXwd0QbUv2YVnDzI5iejVtLmGszHCtj5bFQ

{
    "titulo": "Dúvida sobre Python",
    "conteudo": "Como exatamente funciona o polimorfismo em Python?",
    "curso": 4
}

### Listar Cursos para encontrar um ID
GET http://127.0.0.1:8000/api/cursos/cursos/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzM3NTg1LCJpYXQiOjE3NTEzMDg3ODUsImp0aSI6IjEwZWNlNTUwYjM0MjRjNDM5Y2FlMWU1NDcyZDE0MTg3IiwidXNlcl9pZCI6NH0.PfJaya9fKXwd0QbUv2YVnDzI5iejVtLmGszHCtj5bFQ

### Listar todas as Postagens do Fórum
GET http://127.0.0.1:8000/api/cursos/postagens/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzM3NTg1LCJpYXQiOjE3NTEzMDg3ODUsImp0aSI6IjEwZWNlNTUwYjM0MjRjNDM5Y2FlMWU1NDcyZDE0MTg3IiwidXNlcl9pZCI6NH0.PfJaya9fKXwd0QbUv2YVnDzI5iejVtLmGszHCtj5bFQ


### Listar Todas as Postagens (Para Testar Otimização)
GET http://127.0.0.1:8000/api/cursos/postagens/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMzM3NTg1LCJpYXQiOjE3NTEzMDg3ODUsImp0aSI6IjEwZWNlNTUwYjM0MjRjNDM5Y2FlMWU1NDcyZDE0MTg3IiwidXNlcl9pZCI6NH0.PfJaya9fKXwd0QbUv2YVnDzI5iejVtLmGszHCtj5bFQ


### Teste de Filtro: Buscar posts apenas do Curso de ID 4
GET http://127.0.0.1:8000/api/cursos/postagens/?curso=4
SSSSAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMjM2NDM5LCJpYXQiOjE3NTEzNzI0MzksImp0aSI6IjQ5ZDliYTRiYTU0NTQwNTZiMzM1ZTgzNjE0OTc1ZTA1IiwidXNlcl9pZCI6NH0.6H7dCy-0xuf1gWx4LThJnfNDGeza4Pt2kXQ-9JuoTXg