
### Login como admin
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzNTk2MzU5LCJpYXQiOjE3NTIwNjAzNTksImp0aSI6IjE0NTUyMTI5Mzk3MzRlOGQ5ZTNhMjAyZDY1M2E2MDJkIiwidXNlcl9pZCI6MX0.4FrRxdL8QF-_fG2gpV5ehtsFs8qb-s-RUNWk5rlWAkE
### Login como aluno_novo
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzNTk2NDIyLCJpYXQiOjE3NTIwNjA0MjIsImp0aSI6IjliZjlkZjJmMjk3NTRhYzhiYTY4ZmQwYjAwMDg2YzMzIiwidXNlcl9pZCI6MTN9.tjZfgF7dbPRv_nftNPCc6S1jzaeWRk7jteGa8iy0Sog
### Login como aluno_lento
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzNTk2Mzg5LCJpYXQiOjE3NTIwNjAzODksImp0aSI6IjJlNTI2ZTRkNjUzNTRhNzBiZTI3ZGJlMTdlZDA5ZDUxIiwidXNlcl9pZCI6MTF9.2UPPQcWOOCDFBbmWE-q6rojVkxoF82q8euUQ0oEf1hY
### Login como Professor
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzNjEzMDcwLCJpYXQiOjE3NTIwNzcwNzAsImp0aSI6ImU4NzJhMjIzYjg1NTQ1ZTc4YzYzNjRkZDc4OGZhMjRiIiwidXNlcl9pZCI6MTJ9.mlAkrpLMsn4RI4BO9l5Ei4brkYUnf3dc6U02W-25PXc
### Login como Aluno_gamer
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzNjEzNDcyLCJpYXQiOjE3NTIwNzc0NzIsImp0aSI6IjRjZTYyNjhjZjYxNjRkYjk4ODg4ODFlODRlNjBiMTg4IiwidXNlcl9pZCI6NH0.eur-slsX7L-pyd-rfWjCp2A4M99bmc9XrK6GWWZpfL4

POST http://127.0.0.1:8000/api/auth/token/
Content-Type: application/json

{
    "username": "aluno_gamer",
    "password": "1234"
}


### TENTAR Listar Recursos (como Aluno)
GET http://127.0.0.1:8000/api/biblioteca/recursos/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzNjEzNDcyLCJpYXQiOjE3NTIwNzc0NzIsImp0aSI6IjRjZTYyNjhjZjYxNjRkYjk4ODg4ODFlODRlNjBiMTg4IiwidXNlcl9pZCI6NH0.eur-slsX7L-pyd-rfWjCp2A4M99bmc9XrK6GWWZpfL4