# Generated by Django 5.2.3 on 2025-07-02 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(upload_to='recursos_professores/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(limit_choices_to={'tipo': 'PROFESSOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_upload'],
            },
        ),
    ]
