# Generated by Django 5.2.3 on 2025-07-03 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('cursos', '0006_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos_biblioteca', to='cursos.curso'),
        ),
    ]
