# Generated by Django 5.2.3 on 2025-06-26 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aulaconcluida',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aulaconcluida',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.aula'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='cursos_inscritos', through='cursos.Inscricao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='aula',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='cursos.modulo'),
        ),
        migrations.AlterUniqueTogether(
            name='aulaconcluida',
            unique_together={('aluno', 'aula')},
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('aluno', 'curso')},
        ),
    ]
