# Generated by Django 5.2.3 on 2025-06-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_postagem_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data_edicao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
