# Generated by Django 5.2.3 on 2025-07-08 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_certificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='curso',
            name='alunos',
        ),
        migrations.AddField(
            model_name='postagem',
            name='data_edicao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='progresso',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='cursos.curso'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Ex: 'Turma 2025.1'", max_length=100)),
                ('alunos', models.ManyToManyField(blank=True, related_name='turmas_inscritas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='cursos.curso')),
            ],
        ),
        migrations.AddField(
            model_name='postagem',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='cursos.turma'),
        ),
    ]
