# Generated by Django 5.2.3 on 2025-07-03 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicaoDigitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Ex: 'Frases Curtas', 'Parágrafo Técnico'", max_length=100)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoDigitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavras_por_minuto', models.PositiveIntegerField()),
                ('precisao', models.FloatField(help_text='Ex: 98.5 para 98.5% de precisão')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_digitacao', to=settings.AUTH_USER_MODEL)),
                ('licao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitacao.licaodigitacao')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
