# Generated by Django 5.2.3 on 2025-07-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licaodigitacao',
            name='dificuldade',
            field=models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIO', 'Médio'), ('DIFICIL', 'Difícil')], default='FACIL', max_length=10),
        ),
    ]
