# Generated by Django 5.2.3 on 2025-07-01 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('RESPONSAVEL', 'Responsável'), ('PROFESSOR', 'Professor')], default='ALUNO', max_length=11),
        ),
        migrations.CreateModel(
            name='ResponsavelAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis_associados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(limit_choices_to={'tipo': 'RESPONSAVEL'}, on_delete=django.db.models.deletion.CASCADE, related_name='alunos_associados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('responsavel', 'aluno')},
            },
        ),
    ]
