# Generated by Django 5.2.3 on 2025-06-30 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(help_text='Explique o que o aluno precisa fazer para ganhar.')),
                ('icone', models.CharField(help_text='ex: fas fa-star, fas fa-trophy', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConquistaDoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_obtencao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to=settings.AUTH_USER_MODEL)),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao.conquista')),
            ],
            options={
                'unique_together': {('aluno', 'conquista')},
            },
        ),
    ]
