# Generated by Django 5.2.3 on 2025-07-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0006_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialComplementar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('VIDEO', 'Vídeo'), ('ARTIGO', 'Artigo'), ('LIVRO', 'Livro/PDF'), ('OUTRO', 'Outro')], default='VIDEO', max_length=10)),
                ('link', models.URLField()),
                ('descricao', models.TextField(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_complementares', to='cursos.curso')),
            ],
        ),
    ]
